packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@swc/core': true
  better-sqlite3: false
  esbuild: true
  electron: true

minimumReleaseAgeExclude:
  - framer-motion@13.2.0
  - motion-dom@13.2.0
  - motion@13.2.0
